png(filename="average_open_rate_click_GR40.png",width=1800,height=950,res=300)
new_total<-read.csv("location country code statistics open click gr0.4.csv",head=TRUE)
new_total1<-read.csv("location country code statistics open click.csv",head=TRUE)
data_1<-(new_total1$stats_avg_open_rate)
data_2<-(new_total1$stats_avg_click_rate)
data_3<-(new_total1$location_country_code)
bp=barplot(as.matrix(new_total),las=2,horiz=TRUE,main="Location with open and click rate (Open rate >40%) ",col=c("orange","green"),cex.names=0.6,cex.axis = 0.6,beside=TRUE,xlab="Country Code",ylab="Open VS Click Rate",cex.lab=0.6,cex.main=0.6, ylim=c(0, 1))
legend("top",legend=c("open rate","click rate"),fill=c("orange","green"),ncol=3,bty ="n",cex=0.6)
dev.off()
